"""Added default values to driver_car association table

Revision ID: 47aadc993e77
Revises: 03b7838b8cfe
Create Date: 2024-10-23 09:57:00.947953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47aadc993e77'
down_revision = '03b7838b8cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_car',
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('car_id', sa.Integer(), nullable=False),
        sa.Column('age', sa.Integer(), nullable=False, server_default="25"),
        sa.Column('weight', sa.Float(), nullable=False, server_default="70.0"),
        sa.Column('height', sa.Float(), nullable=False, server_default="175.0"),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
        sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
        sa.PrimaryKeyConstraint('driver_id', 'car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_car')
    # ### end Alembic commands ###
