def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False, server_default="0.0"))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False, server_default="0.0"))

    # Remove the default values after the table is updated
    op.execute('ALTER TABLE driver_car ALTER COLUMN age DROP DEFAULT')
    op.execute('ALTER TABLE driver_car ALTER COLUMN weight DROP DEFAULT')
    op.execute('ALTER TABLE driver_car ALTER COLUMN height DROP DEFAULT')
    # ### end Alembic commands ###
